[package]
name = "simpleca"
version = "0.1.0"
authors = ["Andrey Cizov <acizov@gmail.com>"]
edition = "2018"

[lib]
name = "simpleca"
path = "src/lib.rs"

[[bin]]
name = "simpleca"
path = "src/bin.rs"

[dependencies]
openssl = "0.10.16"
clap = "2.32.0"

[dev-dependencies]
tempfile = "3"